// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkwg5z9n6WW2tlKCwjRxKaLJJsHpBeMU0',
    appId: '1:224431294649:web:342280829459d6670c3368',
    messagingSenderId: '224431294649',
    projectId: 'kp-kumailplastic',
    authDomain: 'kp-kumailplastic.firebaseapp.com',
    storageBucket: 'kp-kumailplastic.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ0q9DHIlWtR8QO6bQflpEUkV9xGgOBs0',
    appId: '1:224431294649:android:20f99cde9101bd6f0c3368',
    messagingSenderId: '224431294649',
    projectId: 'kp-kumailplastic',
    storageBucket: 'kp-kumailplastic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdBi8Nq1X3JiRg4SkYrIB_ic5bgiTQAM8',
    appId: '1:224431294649:ios:e70e74b54f0852ac0c3368',
    messagingSenderId: '224431294649',
    projectId: 'kp-kumailplastic',
    storageBucket: 'kp-kumailplastic.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdBi8Nq1X3JiRg4SkYrIB_ic5bgiTQAM8',
    appId: '1:224431294649:ios:e70e74b54f0852ac0c3368',
    messagingSenderId: '224431294649',
    projectId: 'kp-kumailplastic',
    storageBucket: 'kp-kumailplastic.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkwg5z9n6WW2tlKCwjRxKaLJJsHpBeMU0',
    appId: '1:224431294649:web:fce3139f1f80df360c3368',
    messagingSenderId: '224431294649',
    projectId: 'kp-kumailplastic',
    authDomain: 'kp-kumailplastic.firebaseapp.com',
    storageBucket: 'kp-kumailplastic.appspot.com',
  );
}
